### ISSUE TITLE
fix(nvd): consider versionStartExcluding and versionEndExcluding

### ISSUE THREAD

**Issue by knqyf263** [aquasecurity/avd-generator#81]
`versionStartExcluding` and `versionEndExcluding` should be parsed.
https://github.com/aquasecurity/avd-generator/blob/0ed33499edab1f792678dcbfd7115812122ea436/docGen/nvd.go#L449-L473

**Comment by knqyf263** [comment]
@DmitriyLewen Could you work on it?

**Comment by DmitriyLewen** [comment]
Fixed in #82

**Comment by DmitriyLewen** [comment]
Fixed in #82.
@knqyf263 or @simar7, can you close this issue? I don't have permission to do this.
