### ISSUE TITLE
No space left on device error

### ISSUE THREAD

**Issue by knqyf263** [aquasecurity/avd-generator#99]
It's been failing since 3 days ago.
https://github.com/aquasecurity/avd-generator/actions/runs/11062942445

![CleanShot 2024-09-27 at 13 40 10](https://github.com/user-attachments/assets/25a233f1-c4d2-489a-83eb-b8580a248f8d)

**Comment by simar7** [comment]
https://github.com/aquasecurity/avd-generator/commit/a74cbb046ae1fc3b977585209c7edbe174d215d1 fixed it.
